language: python

os:
    - linux
    - windows


cache: pip

python:
    - "3.8"


matrix:
    fast_finish: true
    allow_failures:
        - os: windows  # allow failure on Win until Travis-Win supports python.


install:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt


# command to run tests
script:
    - pytest --cov=./ --mypy -vv

after_success: coveralls